local o = vim.opt
o.number = true
o.relativenumber = true
o.expandtab = true
o.shiftwidth = 2
o.tabstop = 2
o.smartindent = true
o.ignorecase = true
o.smartcase = true
o.signcolumn = 'yes'
o.undofile = true
o.termguicolors = true
o.splitright = true
o.splitbelow = true
o.clipboard = 'unnamedplus'
o.scrolloff = 8
